# Generated by Django 4.2.4 on 2023-08-05 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='flowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='dataFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='profile/')),
                ('created_at', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='S3Sourecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_access_key_id', models.CharField(max_length=200, unique=True)),
                ('aws_region', models.CharField(max_length=200)),
                ('aws_endpoint_url', models.CharField(max_length=200)),
                ('aws_secret_access_key', models.CharField(max_length=200)),
                ('bucket_name', models.CharField(max_length=200, unique=True)),
                ('file_type', models.CharField(default='csv', max_length=200)),
                ('created_at', models.DateField(auto_now=True)),
                ('dataflows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.dataflow')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosgressSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=20, unique=True)),
                ('host', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=16, unique=True)),
                ('port', models.CharField(default='5423', max_length=5)),
                ('schema', models.CharField(default='public', max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('dataflows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.dataflow')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntervalScheduleSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('interval', models.CharField(choices=[('Minutes', 'Minutes'), ('Hours', 'Hours'), ('Seconds', 'Seconds')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('timezone', models.CharField(choices=[('UTC', 'UTC')], max_length=255)),
                ('dataflows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.dataflow')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='dataflow',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile'),
        ),
    ]
