# Generated by Django 4.2.4 on 2023-08-26 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='flowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='profile/')),
                ('created_at', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingleStoreDB_connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=255)),
                ('single_connection_types', models.CharField(choices=[('Source', 'Source'), ('Target', 'Target')], max_length=10)),
                ('table_name', models.CharField(default='scrap_data', max_length=255)),
                ('singledb_url', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='S3_connections_digital_ocean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=255)),
                ('aws_access_key_id', models.CharField(max_length=200, unique=True)),
                ('aws_region', models.CharField(max_length=200)),
                ('aws_endpoint_url', models.CharField(max_length=200)),
                ('aws_secret_access_key', models.CharField(max_length=200)),
                ('bucket_name', models.CharField(max_length=200, unique=True)),
                ('file_type', models.CharField(default='csv', max_length=200)),
                ('s3_connection_type', models.CharField(choices=[('Source', 'Source'), ('Target', 'Target')], max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='S3_connections_aws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=255)),
                ('aws_access_key_id', models.CharField(max_length=200, unique=True)),
                ('key', models.CharField(max_length=200)),
                ('aws_secret_access_key', models.CharField(max_length=200)),
                ('bucket_name', models.CharField(max_length=200, unique=True)),
                ('file_type', models.CharField(default='csv', max_length=200)),
                ('s3_connection_type', models.CharField(choices=[('Source', 'Source'), ('Target', 'Target')], max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Postgress_connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=255)),
                ('database_name', models.CharField(max_length=20, unique=True)),
                ('host', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=16, unique=True)),
                ('port', models.CharField(default='5423', max_length=5)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('post_connection_type', models.CharField(choices=[('Source', 'Source'), ('Target', 'Target')], max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pinecone_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('environment', models.CharField(max_length=255)),
                ('index_name', models.CharField(max_length=255)),
                ('pincon_connection_types', models.CharField(choices=[('Source', 'Source'), ('Target', 'Target')], max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.s3_connections_aws')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.pinecone_connection')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
