# Generated by Django 4.2.4 on 2023-08-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PosgressSource',
            new_name='PygonSource',
        ),
    ]
