# Generated by Django 4.2.4 on 2023-09-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinecone_connection',
            name='pincon_connection_types',
            field=models.CharField(choices=[('Target', 'Target')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postgress_connections',
            name='post_connection_type',
            field=models.CharField(choices=[('Source', 'Source')], max_length=10),
        ),
        migrations.AlterField(
            model_name='s3_connections_aws',
            name='s3_connection_type',
            field=models.CharField(choices=[('Source', 'Source')], max_length=10),
        ),
        migrations.AlterField(
            model_name='singlestoredb_connections',
            name='single_connection_types',
            field=models.CharField(choices=[('Target', 'Target')], max_length=10),
        ),
        migrations.CreateModel(
            name='Flows_s3_to_singlestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.s3_connections_aws')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.singlestoredb_connections')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flows_postgress_to_singlestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.postgress_connections')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.singlestoredb_connections')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flows_postgress_to_pinecone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.postgress_connections')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.pinecone_connection')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
