# Generated by Django 4.2.4 on 2023-09-07 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureblobContainer_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=255)),
                ('source_name', models.CharField(default='AzureblobContainer', max_length=255)),
                ('conn_str', models.CharField(max_length=255)),
                ('container', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AzureblobStorage_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=255)),
                ('source_name', models.CharField(default='AzureblobStorage', max_length=255)),
                ('conn_str', models.CharField(max_length=255)),
                ('container', models.CharField(max_length=255)),
                ('blob_name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='flows',
            name='source',
            field=models.CharField(choices=[('S3digitalOcean', 'S3digitalOcean'), ('S3', 'S3'), ('Postgress', 'Postgress'), ('Googledrive', 'Googledrive'), ('Github', 'Github'), ('Snowflake', 'Snowflake'), ('AzureblobStorage', 'AzureblobStorage'), ('AzureblobStorage', 'AzureblobStorage')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Azureblob_connection',
        ),
    ]
