# Generated by Django 4.2.4 on 2023-09-08 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0002_azureblobcontainer_connection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flows',
            options={'ordering': ['schedule_time']},
        ),
        migrations.RenameField(
            model_name='flows',
            old_name='scheduel_time',
            new_name='schedule_time',
        ),
    ]
