# Generated by Django 4.2.4 on 2023-08-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0002_rename_posgresssource_pygonsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinecone_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pinecone', max_length=100)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('environment', models.CharField(max_length=255)),
                ('index_name', models.CharField(max_length=255)),
                ('connection_types', models.CharField(choices=[('Source', 'Source'), ('Target', 'Target')], max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Postgress_connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Postgress', max_length=100)),
                ('database_name', models.CharField(max_length=20, unique=True)),
                ('host', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=16, unique=True)),
                ('port', models.CharField(default='5423', max_length=5)),
                ('schema', models.CharField(default='public', max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('connection_type', models.CharField(choices=[('Source', 'Source'), ('Target', 'Target')], max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='S3_connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='S3', max_length=100)),
                ('aws_access_key_id', models.CharField(max_length=200, unique=True)),
                ('aws_region', models.CharField(max_length=200)),
                ('aws_endpoint_url', models.CharField(max_length=200)),
                ('aws_secret_access_key', models.CharField(max_length=200)),
                ('bucket_name', models.CharField(max_length=200, unique=True)),
                ('file_type', models.CharField(default='csv', max_length=200)),
                ('connection_type', models.CharField(choices=[('Source', 'Source'), ('Target', 'Target')], max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SingleStoreDB_connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SingleStoreDB', max_length=100)),
                ('connection_types', models.CharField(choices=[('Source', 'Source'), ('Target', 'Target')], max_length=10)),
                ('singledb_url', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='intervalscheduleschedule',
            name='dataflows',
        ),
        migrations.RemoveField(
            model_name='pygonsource',
            name='dataflows',
        ),
        migrations.RemoveField(
            model_name='s3sourecs',
            name='dataflows',
        ),
        migrations.DeleteModel(
            name='dataFlow',
        ),
        migrations.DeleteModel(
            name='IntervalScheduleSchedule',
        ),
        migrations.DeleteModel(
            name='PygonSource',
        ),
        migrations.DeleteModel(
            name='S3Sourecs',
        ),
    ]
