# Generated by Django 4.2.4 on 2023-08-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0003_pinecone_connection_postgress_connections_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinecone_connection',
            old_name='connection_types',
            new_name='pincon_connection_types',
        ),
        migrations.RenameField(
            model_name='postgress_connections',
            old_name='connection_type',
            new_name='post_connection_type',
        ),
        migrations.RenameField(
            model_name='s3_connections',
            old_name='connection_type',
            new_name='s3_connection_type',
        ),
        migrations.RenameField(
            model_name='singlestoredb_connections',
            old_name='connection_types',
            new_name='single_connection_types',
        ),
        migrations.RemoveField(
            model_name='pinecone_connection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='postgress_connections',
            name='name',
        ),
        migrations.RemoveField(
            model_name='s3_connections',
            name='name',
        ),
        migrations.RemoveField(
            model_name='singlestoredb_connections',
            name='name',
        ),
    ]
