# Generated by Django 4.2.4 on 2023-09-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0003_alter_flows_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notion_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=255)),
                ('source_name', models.CharField(default='Notion', max_length=255)),
                ('integration_token', models.CharField(max_length=255)),
                ('database_id', models.CharField(max_length=255)),
                ('request_timeout_sec', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.userprofile')),
            ],
        ),
    ]
