# Generated by Django 4.2.4 on 2023-08-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0004_rename_connection_types_pinecone_connection_pincon_connection_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgress_connections',
            name='schema',
        ),
    ]
