# Generated by Django 4.2.4 on 2023-08-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0006_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlestoredb_connections',
            name='table_name',
            field=models.CharField(default='scrap_data', max_length=255),
        ),
        migrations.AlterField(
            model_name='flows',
            name='target',
            field=models.CharField(choices=[('Pinecone', 'Pinecone'), ('Postgress', 'Postgress'), ('SingleStore', 'SingleStore')], max_length=255),
        ),
    ]
